# FILE PURPOSE: First migration for the dashboard app so fresh clones already have the ExampleRecord table.
# TEACHING TIP: Treat this file as auto-generated - update it by re-running `python manage.py makemigrations` after model edits.
# Generated by Django 5.2.4 on 2025-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Example Records',
            },
        ),
    ]
